apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "taskflow.fullname" . }}-api
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels.api" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskflow.selectorLabels.api" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.config.port }}
          envFrom:
            - configMapRef:
                name: {{ include "taskflow.fullname" . }}-config
            - secretRef:
                name: {{ include "taskflow.secretName" . }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.config.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
