apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskflow.fullname" . }}-postgres
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "taskflow.selectorLabels.postgres" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "taskflow.fullname" . }}-postgres
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "taskflow.fullname" . }}-postgres
  replicas: 1
  selector:
    matchLabels:
      {{- include "taskflow.selectorLabels.postgres" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "taskflow.selectorLabels.postgres" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "taskflow.secretName" . }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources.postgres | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
